#
# .pre-commit-config file for sm4rth0m3/python-pip.sonoff-ewelink-cube-client-api
#
---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: local
    hooks:
      - id: nbsp-check
        name: check for non-breaking spaces in files
        entry: .pre-commit-hooks/pre-commit-nbsp-check.sh
        language: script

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
          ]
